/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLichRouteImport } from './routes/_authenticated/lich'
import { Route as AuthenticatedDanhSachRouteImport } from './routes/_authenticated/danh-sach'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLichRoute = AuthenticatedLichRouteImport.update({
  id: '/lich',
  path: '/lich',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDanhSachRoute = AuthenticatedDanhSachRouteImport.update({
  id: '/danh-sach',
  path: '/danh-sach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/danh-sach': typeof AuthenticatedDanhSachRoute
  '/lich': typeof AuthenticatedLichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/danh-sach': typeof AuthenticatedDanhSachRoute
  '/lich': typeof AuthenticatedLichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/danh-sach': typeof AuthenticatedDanhSachRoute
  '/_authenticated/lich': typeof AuthenticatedLichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/danh-sach' | '/lich'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/danh-sach' | '/lich'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/danh-sach'
    | '/_authenticated/lich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lich': {
      id: '/_authenticated/lich'
      path: '/lich'
      fullPath: '/lich'
      preLoaderRoute: typeof AuthenticatedLichRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/danh-sach': {
      id: '/_authenticated/danh-sach'
      path: '/danh-sach'
      fullPath: '/danh-sach'
      preLoaderRoute: typeof AuthenticatedDanhSachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDanhSachRoute: typeof AuthenticatedDanhSachRoute
  AuthenticatedLichRoute: typeof AuthenticatedLichRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDanhSachRoute: AuthenticatedDanhSachRoute,
  AuthenticatedLichRoute: AuthenticatedLichRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
